# coding: utf-8

"""
    Read-only API стриминга

    Получение ссылок на файловые ресурсы для стиминга  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import streaming_api
from streaming_api.models.cdn_location import CDNLocation  # noqa: E501
from streaming_api.rest import ApiException


class TestCDNLocation(unittest.TestCase):
    """CDNLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCDNLocation(self):
        """Test CDNLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = streaming_api.models.cdn_location.CDNLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
