# coding: utf-8

"""
    Read-only API стриминга

    Получение ссылок на файловые ресурсы для стиминга  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import streaming_api
from streaming_api.api.health_api import HealthApi  # noqa: E501
from streaming_api.rest import ApiException


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self):
        self.api = HealthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_check_streaming_api_api_health_check_get(self):
        """Test case for health_check_streaming_api_api_health_check_get

        Health Check  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
