# coding: utf-8

"""
    Read-only API стриминга

    Получение ссылок на файловые ресурсы для стиминга  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CDNLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'region': 'str',
        'cdn': 'AllOfCDNLocationCdn'
    }

    attribute_map = {
        'id': 'id',
        'region': 'region',
        'cdn': 'cdn'
    }

    def __init__(self, id=None, region=None, cdn=None):  # noqa: E501
        """CDNLocation - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._region = None
        self._cdn = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.region = region
        if cdn is not None:
            self.cdn = cdn

    @property
    def id(self):
        """Gets the id of this CDNLocation.  # noqa: E501


        :return: The id of this CDNLocation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CDNLocation.


        :param id: The id of this CDNLocation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def region(self):
        """Gets the region of this CDNLocation.  # noqa: E501


        :return: The region of this CDNLocation.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this CDNLocation.


        :param region: The region of this CDNLocation.  # noqa: E501
        :type: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def cdn(self):
        """Gets the cdn of this CDNLocation.  # noqa: E501


        :return: The cdn of this CDNLocation.  # noqa: E501
        :rtype: AllOfCDNLocationCdn
        """
        return self._cdn

    @cdn.setter
    def cdn(self, cdn):
        """Sets the cdn of this CDNLocation.


        :param cdn: The cdn of this CDNLocation.  # noqa: E501
        :type: AllOfCDNLocationCdn
        """

        self._cdn = cdn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CDNLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CDNLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
