# coding: utf-8

"""
    Read-only API стриминга

    Получение ссылок на файловые ресурсы для стиминга  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MediaLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cdn_location': 'CDNLocation',
        'media_id': 'str'
    }

    attribute_map = {
        'cdn_location': 'cdn_location',
        'media_id': 'media_id'
    }

    def __init__(self, cdn_location=None, media_id=None):  # noqa: E501
        """MediaLocation - a model defined in Swagger"""  # noqa: E501
        self._cdn_location = None
        self._media_id = None
        self.discriminator = None
        self.cdn_location = cdn_location
        self.media_id = media_id

    @property
    def cdn_location(self):
        """Gets the cdn_location of this MediaLocation.  # noqa: E501


        :return: The cdn_location of this MediaLocation.  # noqa: E501
        :rtype: CDNLocation
        """
        return self._cdn_location

    @cdn_location.setter
    def cdn_location(self, cdn_location):
        """Sets the cdn_location of this MediaLocation.


        :param cdn_location: The cdn_location of this MediaLocation.  # noqa: E501
        :type: CDNLocation
        """
        if cdn_location is None:
            raise ValueError("Invalid value for `cdn_location`, must not be `None`")  # noqa: E501

        self._cdn_location = cdn_location

    @property
    def media_id(self):
        """Gets the media_id of this MediaLocation.  # noqa: E501


        :return: The media_id of this MediaLocation.  # noqa: E501
        :rtype: str
        """
        return self._media_id

    @media_id.setter
    def media_id(self, media_id):
        """Sets the media_id of this MediaLocation.


        :param media_id: The media_id of this MediaLocation.  # noqa: E501
        :type: str
        """
        if media_id is None:
            raise ValueError("Invalid value for `media_id`, must not be `None`")  # noqa: E501

        self._media_id = media_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MediaLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
